// Dari (Afghan Persian) text for the report library. Kept in its own module
// rather than appended to lib/strings.ts so the catalog can grow without every
// report touching the file every other screen imports.
export const RT = {
  // ---------- chrome ----------
  library: 'کتابخانه گزارش‌ها',
  librarySub: 'گزارش‌های تفصیلی با فیلتر، مرتب‌سازی و خروجی',
  dashboard: 'داشبورد گزارش‌ها',
  dashboardSub: 'نمای کلی و شاخص‌های خلاصه',
  searchReports: 'جستجوی گزارش…',
  noReportFound: 'گزارشی با این نام پیدا نشد',
  backToLibrary: 'کتابخانه گزارش‌ها',
  openReport: 'باز کردن',
  reportCount: 'گزارش',

  // periods
  periodWeek: '۷ روز',
  periodMonth: '۳۰ روز',
  periodQuarter: '۹۰ روز',
  periodYear: 'یک سال',
  periodAll: 'همه',
  periodLabel: 'دوره',
  scopeMe: 'من',
  scopeTeam: 'تیم',
  since: 'از',
  untilNow: 'تا امروز',
  allTime: 'از ابتدا',

  // toolbar
  groupBy: 'گروه‌بندی',
  noGrouping: 'بدون گروه‌بندی',
  exportCsv: 'خروجی CSV',
  refresh: 'تازه‌سازی',
  rowCount: 'تعداد ردیف',
  rows: 'ردیف',
  dayUnit: 'روز',
  noValue: 'بدون مقدار',
  noRows: 'داده‌ای برای این گزارش در این دوره نیست',
  partialData: 'داده‌ها ناقص خوانده شد (سقف صفحه‌بندی) — اعداد کمتر از واقعیت‌اند',
  notProvisioned:
    'این گزارش به آبجکتی نیاز دارد که در این محیط ساخته نشده است؛ اسکریپت تهیه (provisioning) باید اجرا شود.',
  loadFailed: 'بارگذاری گزارش ناموفق بود',

  // ---------- categories ----------
  catPipeline: 'قیف فروش',
  catPerformance: 'عملکرد',
  catRevenue: 'درآمد',
  catActivity: 'فعالیت',

  // ---------- shared column labels ----------
  colLead: 'لید',
  colCompany: 'شرکت',
  colContact: 'شخص تماس',
  colPhone: 'تلفن',
  colStage: 'مرحله',
  colOwner: 'مسئول',
  colSource: 'منبع',
  colTemperature: 'علاقمندی',
  colValue: 'ارزش',
  colCreated: 'تاریخ ثبت',
  colAge: 'عمر لید',
  colDaysInStage: 'روز در این مرحله',
  colStageSince: 'آخرین تغییر مرحله',
  colHealth: 'وضعیت',
  colReferrer: 'معرف',
  colMarketer: 'بازاریاب',
  colRegisteredBy: 'ثبت‌کننده',
  colSeller: 'فروشنده',
  colLeads: 'لید',
  colWon: 'برنده',
  colLost: 'از دست رفته',
  colOpen: 'باز',
  colWinRate: 'نرخ موفقیت',
  colPipeline: 'قیف باز',
  colWonValue: 'ارزش برنده‌شده',
  colTasksDone: 'کار انجام‌شده',
  colTasksPerLead: 'کار به ازای لید',
  colProduct: 'محصول',
  colQuantity: 'تعداد',
  colInstall: 'قیمت نصب',
  colAnnual: 'قیمت سالانه',
  colLineTotal: 'مجموع خط',
  colDiscount: 'تخفیف',
  colAvgDiscount: 'میانگین تخفیف',
  colMaxDiscount: 'بیشترین تخفیف',
  colDiscountedLines: 'خطوط تخفیف‌دار',
  colUnits: 'واحد فروخته‌شده',
  colLines: 'خطوط معامله',
  colDate: 'تاریخ',
  colTask: 'کار',
  colTaskType: 'نوع کار',
  colAssignee: 'مسئول کار',
  colDue: 'موعد',
  colOverdue: 'روز تأخیر',
  colStatus: 'وضعیت',
  colOutcome: 'نتیجه',
  colClosedAt: 'تاریخ بسته‌شدن',
  colDaysToClose: 'طول چرخه',
  colCycleBucket: 'بازه چرخه',
  colLastActivity: 'آخرین فعالیت',
  colDaysSilent: 'روز بدون تماس',
  colPartner: 'همکار',
  colPartnerType: 'نوع همکار',
  colCommissionRate: 'نرخ کمیسیون',
  colCommissionDue: 'کمیسیون برآوردی',
  colCustomer: 'مشتری',
  colBillingPeriod: 'دوره صورتحساب',
  colRecurring: 'مبلغ تکراری',
  colAnnualized: 'ارزش سالانه',
  colStart: 'شروع',
  colEnd: 'پایان',
  colAutoRenew: 'تمدید خودکار',
  colDaysToRenewal: 'روز تا تمدید',
  colOfferedAt: 'تاریخ پیشنهاد',
  colOfferedBy: 'پیشنهاددهنده',
  colAmount: 'مبلغ',
  colSubmitted: 'روزهای ثبت‌شده',
  colExpected: 'روزهای کاری',
  colComplianceRate: 'درصد ثبت',
  colLastSubmission: 'آخرین ثبت',
  colAvgReported: 'میانگین کار گزارش‌شده',
  colSummary: 'خلاصه',

  // ---------- shared values ----------
  won: 'برنده',
  lost: 'از دست رفته',
  open: 'باز',
  yes: 'بلی',
  no: 'نخیر',
  healthFresh: 'تازه',
  healthWatch: 'نیازمند پیگیری',
  healthStale: 'راکد',
  overdueLabel: 'عقب‌مانده',
  dueToday: 'امروز',
  dueSoon: 'این هفته',
  dueLater: 'بعداً',
  noDue: 'بدون موعد',
  cycleFast: 'کمتر از ۷ روز',
  cycleNormal: '۷ تا ۳۰ روز',
  cycleSlow: '۳۰ تا ۹۰ روز',
  cycleVerySlow: 'بیش از ۹۰ روز',
  noLead: 'بدون لید',
  subActive: 'فعال',
  subPending: 'در انتظار',
  subExpired: 'منقضی',
  subCancelled: 'لغو شده',
  billingMonthly: 'ماهانه',
  billingAnnual: 'سالانه',
  offerProposed: 'ارائه شده',
  offerAccepted: 'پذیرفته شده',
  offerRejected: 'رد شده',
  offerSuperseded: 'جایگزین شده',
  roleFinder: 'یابنده',
  roleIntroducer: 'معرفی‌کننده',
  roleCloser: 'بستن معامله',
  roleOther: 'سایر',
  primaryReferrer: 'معرف اصلی',

  // ---------- report titles and descriptions ----------
  rPipelineTitle: 'فهرست قیف باز',
  rPipelineDesc:
    'هر لید باز با مرحله، مسئول، ارزش و عمر آن — پایه‌ی هر مرور قیف فروش.',
  rAgingTitle: 'کهنگی مراحل',
  rAgingDesc:
    'چند روز است هر لید در مرحله فعلی مانده و کدام‌ها راکد شده‌اند.',
  rSilentTitle: 'لیدهای بدون پیگیری',
  rSilentDesc:
    'لیدهای بازی که مدت‌هاست هیچ کاری روی‌شان انجام یا ثبت نشده است.',
  rRegisterTitle: 'دفتر ثبت لیدها',
  rRegisterDesc:
    'همه لیدهای ثبت‌شده در دوره، با شخص تماس، منبع، معرف و ثبت‌کننده.',
  rSellerTitle: 'کارنامه فروشندگان',
  rSellerDesc:
    'لید، برد، باخت، نرخ موفقیت، قیف باز و حجم کار هر فروشنده در دوره.',
  rMarketerTitle: 'عملکرد بازاریابان',
  rMarketerDesc:
    'لیدهای آورده‌شده توسط هر بازاریاب و اینکه چند تای آن‌ها مشتری شد.',
  rSourceTitle: 'اثربخشی منابع',
  rSourceDesc:
    'هر منبع لید چقدر لید آورد، چقدر از آن برنده شد و چقدر طول کشید.',
  rWinLossTitle: 'تحلیل برد و باخت',
  rWinLossDesc:
    'معاملات بسته‌شده دوره با نتیجه، ارزش، منبع و طول چرخه فروش.',
  rCycleTitle: 'طول چرخه فروش',
  rCycleDesc:
    'برای هر معامله برنده‌شده، فاصله ثبت تا بستن و توزیع آن در بازه‌ها.',
  rProductTitle: 'درآمد محصولات',
  rProductDesc:
    'هر خط محصول در معاملات دوره: تعداد، قیمت نصب، قیمت سالانه و تخفیف.',
  rDiscountTitle: 'تحلیل تخفیف',
  rDiscountDesc:
    'میانگین و بیشترین تخفیف هر محصول و سهم خطوط تخفیف‌دار.',
  rCommissionTitle: 'کمیسیون معرفان',
  rCommissionDesc:
    'لیدهای هر معرف/همکار و کمیسیون برآوردی از معاملات برنده‌شده.',
  rSubscriptionTitle: 'اشتراک‌ها و درآمد تکراری',
  rSubscriptionDesc:
    'اشتراک‌های فعال، مبلغ تکراری، ارزش سالانه و تاریخ تمدید.',
  rOfferTitle: 'پیشنهادهای قیمت',
  rOfferDesc:
    'پیشنهادهای ثبت‌شده در دوره با وضعیت پذیرش و نرخ قبولی.',
  rActivityTitle: 'دفتر فعالیت',
  rActivityDesc:
    'هر کار انجام‌شده در دوره با نوع، فروشنده و لید مربوط.',
  rSlaTitle: 'کارهای عقب‌مانده',
  rSlaDesc:
    'کارهای باز با موعد گذشته یا نزدیک، به تفکیک مسئول و میزان تأخیر.',
  rDailyTitle: 'انضباط گزارش روزانه',
  rDailyDesc:
    'هر فروشنده چند روز از دوره را گزارش روزانه ثبت کرده است.',

  // ---------- KPI labels ----------
  kOpenLeads: 'لید باز',
  kPipelineValue: 'ارزش قیف',
  kAvgValue: 'میانگین ارزش',
  kAvgAge: 'میانگین عمر',
  kHotLeads: 'لید داغ',
  kStale: 'لید راکد',
  kOldest: 'کهنه‌ترین',
  kAvgDaysInStage: 'میانگین روز در مرحله',
  kSilent14: 'بیش از ۱۴ روز سکوت',
  kSilent30: 'بیش از ۳۰ روز سکوت',
  kRegistered: 'لید ثبت‌شده',
  kTotalValue: 'مجموع ارزش',
  kWithContact: 'دارای شخص تماس',
  kSellers: 'فروشنده فعال',
  kTeamWon: 'برنده تیم',
  kTeamWinRate: 'نرخ موفقیت تیم',
  kTeamTasks: 'کار انجام‌شده',
  kMarketers: 'بازاریاب',
  kSources: 'منبع',
  kBestSource: 'بهترین منبع',
  kClosed: 'معامله بسته‌شده',
  kWinRate: 'نرخ موفقیت',
  kWonValue: 'ارزش برنده‌شده',
  kLostValue: 'ارزش از دست رفته',
  kAvgCycle: 'میانگین چرخه',
  kMedianCycle: 'میانه چرخه',
  kFastest: 'سریع‌ترین',
  kSlowest: 'کندترین',
  kLines: 'خط معامله',
  kUnits: 'واحد',
  kInstallRevenue: 'درآمد نصب',
  kAnnualRevenue: 'درآمد سالانه',
  kAvgDiscount: 'میانگین تخفیف',
  kDiscountedShare: 'سهم خطوط تخفیف‌دار',
  kPartners: 'همکار',
  kCommissionDue: 'کمیسیون برآوردی',
  kActiveSubs: 'اشتراک فعال',
  kAnnualized: 'ارزش سالانه',
  kRenewals60: 'تمدید تا ۶۰ روز',
  kOffers: 'پیشنهاد',
  kAccepted: 'پذیرفته‌شده',
  kAcceptRate: 'نرخ پذیرش',
  kTasksDone: 'کار انجام‌شده',
  kPerDay: 'به‌طور میانگین در روز',
  kTopType: 'پرتکرارترین نوع',
  kTopSeller: 'فعال‌ترین فروشنده',
  kOverdue: 'عقب‌مانده',
  kDueToday: 'موعد امروز',
  kNoDue: 'بدون موعد',
  kWorstDelay: 'بیشترین تأخیر',
  kCompliance: 'میانگین درصد ثبت',
  kReportDays: 'روز گزارش‌شده',
};
