import { useState } from 'react';

import { type CampaignFormOption } from '../../../api/surveyInsights';
import { type SurveyCampaign } from '../../../api/surveys';
import { TINS } from '../../../lib/forms/insightStrings';

export const attributionLink = (publicSlug: string, publicCode: string): string =>
  `${window.location.origin}/sales/#/f/${encodeURIComponent(publicSlug)}?c=${encodeURIComponent(publicCode)}`;

const CopyButton = ({ text }: { text: string }) => {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard can be blocked (insecure origin, permissions); the text
      // stays selectable, so there is nothing else to do.
    }
  };

  return (
    <button type="button" className="btn line sm" onClick={() => void copy()} aria-live="polite">
      {copied ? TINS.copied : TINS.copy}
    </button>
  );
};

// The opaque &c= code (generated by the server, never editable) and a ready
// link per attached form. Uses the SAVED campaign: unsaved form changes are
// not yet something the server would honour.
export const CampaignAttribution = ({
  campaign,
  forms,
}: {
  campaign: SurveyCampaign;
  forms: CampaignFormOption[];
}) => {
  const attached = campaign.formIds
    .map((formId) => forms.find((form) => form.id === formId))
    .filter((form): form is CampaignFormOption => form !== undefined);

  return (
    <section className="card card-pad svk-attribution" aria-labelledby="svk-attr-title">
      <h3 id="svk-attr-title">{TINS.attribution}</h3>
      {campaign.publicCode === '' ? (
        <p className="svk-note">{TINS.codePending}</p>
      ) : (
        <div className="svk-code-row">
          <code dir="ltr">{campaign.publicCode}</code>
          <CopyButton text={campaign.publicCode} />
        </div>
      )}
      <p className="svk-note">{TINS.attributionHelp}</p>
      {campaign.campaignStatus !== 'ACTIVE' && (
        <p className="svk-warn" role="status">
          {TINS.attributionInactive}
        </p>
      )}
      <h4>{TINS.exampleLinks}</h4>
      {attached.length === 0 || campaign.publicCode === '' ? (
        <div className="svk-muted-note">{TINS.noFormLinks}</div>
      ) : (
        <ul className="svk-links">
          {attached.map((form) => {
            const link = attributionLink(form.publicSlug, campaign.publicCode);

            return (
              <li key={form.id}>
                <span className="svk-link-name" dir="auto">
                  {form.name}
                </span>
                <div className="svk-code-row">
                  <input readOnly dir="ltr" value={link} aria-label={form.name} onFocus={(event) => event.target.select()} />
                  <CopyButton text={link} />
                </div>
                {form.formStatus !== 'PUBLISHED' && <small className="svk-warn">{TINS.unpublishedFormLink}</small>}
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
};
