import {
  type AutomationAction,
  type ConditionOperator,
  type CrmTargetField,
  type FileTypeGroup,
  type FormPresentation,
} from '@shared/surveys';

import { toPersianDigits } from '../jalali';
import { type AutosaveStatus } from './builder/autosave';
import { type StatusActionKind } from './builder/formsList';
import { type WorkspaceTab } from './builder/issues';
import { type RuleReferenceKind } from './builder/references';

// Staff-facing text of the forms list, template gallery, builder workspace
// and preview. Dari only (house rule).

const n = (value: number | string) => toPersianDigits(String(value));

export const TB = {
  // list
  listTitle: 'فرم‌ها و نظرسنجی‌ها',
  filterStatus: 'وضعیت',
  filterOwner: 'مسئول',
  filterPurpose: 'هدف',
  filterCampaign: 'کمپاین',
  statusActive: 'همه به‌جز بایگانی',
  statusAll: 'همه (با بایگانی)',
  anyOwner: 'همهٔ مسئولان',
  anyPurpose: 'همهٔ هدف‌ها',
  anyCampaign: 'همهٔ کمپاین‌ها',
  sort: 'مرتب‌سازی',
  view: 'نمایش',
  noMatch: 'فرمی با این فیلترها پیدا نشد.',
  clearFilters: 'پاک کردن فیلترها',
  archivedHidden: (count: number) => `${n(count)} فرم بایگانی‌شده پنهان است`,
  showArchived: 'نمایش بایگانی',
  actions: 'کارها',
  moreActions: (name: string) => `کارهای بیشتر برای «${name}»`,
  versionN: (version: number) => `نسخهٔ ${n(version)}`,
  responsesN: (count: number) => `${n(count)} پاسخ`,
  duplicating: 'در حال کپی…',
  duplicated: 'کپی ساخته شد',
  statusChanged: 'وضعیت فرم تغییر کرد',
  actionFailed: 'انجام نشد',
  noOwner: '—',
  untitled: 'فرم بی‌نام',
  // status actions
  statusAction: {
    close: 'بستن فرم',
    reopen: 'بازگشایی فرم',
    archive: 'بایگانی',
    unarchive: 'بازگردانی از بایگانی',
  } satisfies Record<StatusActionKind, string>,
  statusConfirm: {
    close: 'فرم بسته می‌شود و لینک عمومی دیگر پاسخ نمی‌پذیرد. پاسخ‌های ثبت‌شده حفظ می‌شوند.',
    reopen: 'فرم دوباره باز می‌شود و لینک عمومی آخرین نسخهٔ منتشرشده را نشان می‌دهد.',
    archive:
      'فرم بایگانی و از فهرست اصلی پنهان می‌شود. پاسخ‌ها و نسخه‌ها حذف نمی‌شوند و هر وقت بخواهید قابل بازگردانی است.',
    unarchive: 'فرم از بایگانی بیرون می‌آید.',
  } satisfies Record<StatusActionKind, string>,
  archiveInsteadOfDelete: 'فرم‌ها حذف نمی‌شوند؛ برای کنار گذاشتن از بایگانی استفاده کنید.',

  // templates
  templatesTitle: 'فرم جدید',
  templatesSub: 'از یک فرم خالی یا یکی از الگوهای آماده شروع کنید؛ همه‌چیز بعداً قابل ویرایش است.',
  blankForm: 'فرم خالی',
  blankFormDescription: 'یک صفحهٔ خالی و یک پیام پایانی — از صفر بسازید.',
  pagesN: (count: number) => `${n(count)} صفحه`,
  questionsN: (count: number) => `${n(count)} سؤال`,
  useTemplate: 'استفاده از این الگو',
  createFormTitle: 'ساخت فرم',
  formName: 'نام فرم',
  formNameRequired: 'نام فرم را بنویسید.',
  create: 'ساخت و باز کردن سازنده',
  creating: 'در حال ساخت…',
  createFailed: 'ساخت فرم انجام نشد.',
  noBuildPermission: 'برای ساخت فرم اجازه ندارید.',

  // workspace header
  tabs: {
    builder: 'سازنده',
    logic: 'منطق',
    appearance: 'ظاهر',
    crm: 'CRM و خودکارسازی',
    settings: 'تنظیمات',
    share: 'اشتراک‌گذاری',
    responses: 'پاسخ‌ها',
    insights: 'تحلیل',
  } satisfies Record<WorkspaceTab, string>,
  tabsLabel: 'بخش‌های فرم',
  autosave: {
    idle: 'همه‌چیز ذخیره است',
    pending: 'تغییرات ذخیره‌نشده',
    saving: 'در حال ذخیره…',
    saved: 'ذخیره شد',
    error: 'ذخیره نشد',
    conflict: 'ذخیره متوقف شد',
  } satisfies Record<AutosaveStatus, string>,
  retrySave: 'تلاش دوباره',
  readOnly: 'فقط مشاهده — اجازهٔ ویرایش این فرم را ندارید.',
  archivedReadOnly: 'این فرم بایگانی است؛ برای ویرایش ابتدا آن را از بایگانی بیرون بیاورید.',
  conflictTitle: 'این فرم در جای دیگری ویرایش شده است',
  conflictBody:
    'کسی (یا همین شما در زبانهٔ دیگر) پیش‌نویس را ذخیره کرده است. ذخیرهٔ خودکار متوقف شد تا کار هیچ‌کس پاک نشود. پیش از بارگذاری دوباره می‌توانید تغییرات خود را کپی کنید.',
  copyMyChanges: 'کپی تغییرات من (JSON)',
  copied: 'کپی شد',
  copyFailed: 'کپی نشد',
  reloadDraft: 'بارگذاری نسخهٔ سرور',
  unsavedLeave: 'تغییرات هنوز ذخیره نشده‌اند.',
  loadFailed: 'فرم بارگذاری نشد.',
  notFound: 'این فرم پیدا نشد.',
  publishNeedsSave: 'اول باید تغییرات ذخیره شوند.',
  pathHint: 'ساخت ← پیش‌نمایش ← انتشار ← اشتراک ← پاسخ‌ها',

  // publish dialog
  publishTitle: 'انتشار فرم',
  publishAsVersion: (version: number) => `انتشار به‌عنوان نسخهٔ ${n(version)}`,
  publishNow: 'انتشار',
  publishing: 'در حال انتشار…',
  publishErrors: 'این موارد مانع انتشار است:',
  publishWarnings: 'هشدارها (مانع انتشار نیست):',
  publishReady: 'فرم آمادهٔ انتشار است.',
  changeNote: 'یادداشت تغییرات (اختیاری)',
  changeNotePlaceholder: 'مثلاً: سؤال «نرم‌افزار فعلی» اضافه شد',
  republishTitle: 'انتشار دوباره چه اثری دارد؟',
  republishRules: [
    'لینک عمومی همیشه جدیدترین نسخهٔ منتشرشده را نشان می‌دهد.',
    'کسی که فرم را با نسخهٔ قبلی باز کرده، همان نسخه را تمام می‌کند و پاسخش از دست نمی‌رود.',
    'نسخه‌های چاپی کد نسخهٔ خود را دارند و هنگام ورود پاسخ کاغذی همان نسخه انتخاب می‌شود.',
    'گزارش‌ها نسخه‌ها را بر اساس شناسهٔ سؤال کنار هم می‌گذارند؛ سؤالی که در یک نسخه نبود «در این نسخه نبود» شمرده می‌شود، نه بی‌پاسخ.',
  ],
  published: (version: number) => `نسخهٔ ${n(version)} منتشر شد.`,
  goShare: 'رفتن به اشتراک‌گذاری',
  publishFailed: 'انتشار انجام نشد.',
  serverIssues: 'سرور این مشکلات را گزارش کرد:',

  // palette
  palette: 'افزودن',
  paletteGroups: {
    text: 'متن',
    choice: 'انتخابی',
    dateNumber: 'تاریخ و عدد',
    scales: 'مقیاس',
    contact: 'تماس، مکان، فایل و رضایت',
    display: 'نمایشی و بخش',
    staff: 'فقط کارمندان (CRM)',
  },
  staffOnlyGroupHint: 'این پرسش‌ها در فرم عمومی نمایش داده نمی‌شوند.',
  addToPage: (label: string) => `افزودن «${label}» به صفحهٔ انتخاب‌شده`,
  blockLabels: {
    section: 'بخش',
    heading: 'عنوان',
    paragraph: 'متن توضیحی',
    image: 'تصویر',
    divider: 'خط جداکننده',
  },

  // canvas
  page: 'صفحه',
  pageN: (index: number) => `صفحهٔ ${n(index)}`,
  pageTitlePlaceholder: 'عنوان صفحه (اختیاری)',
  addPage: 'افزودن صفحه',
  duplicatePage: 'کپی صفحه',
  deletePage: 'حذف صفحه',
  movePageUp: (index: number) => `انتقال صفحهٔ ${n(index)} به بالا`,
  movePageDown: (index: number) => `انتقال صفحهٔ ${n(index)} به پایین`,
  pageSettings: (index: number) => `تنظیمات صفحهٔ ${n(index)}`,
  emptyPage: 'این صفحه خالی است — از فهرست «افزودن» یک سؤال انتخاب کنید یا آن را اینجا بکشید.',
  dropHere: 'اینجا رها کنید',
  moveUp: (label: string) => `انتقال «${label}» به بالا`,
  moveDown: (label: string) => `انتقال «${label}» به پایین`,
  moveToPage: 'انتقال به صفحه…',
  moveToPageLabel: (label: string) => `انتقال «${label}» به صفحهٔ دیگر`,
  duplicateItem: (label: string) => `کپی «${label}»`,
  deleteItem: (label: string) => `حذف «${label}»`,
  selectItem: (label: string) => `انتخاب «${label}» برای ویرایش`,
  dragHandle: (label: string) => `جابه‌جایی «${label}» با کشیدن`,
  logicBadge: 'منطق',
  logicBadgeTitle: 'این مورد شرط نمایش یا الزام دارد',
  staffBadge: 'فقط کارمندان',
  requiredMark: 'الزامی',
  noLabel: 'بدون عنوان',
  jumpsN: (count: number) => `${n(count)} قاعدهٔ پرش`,

  // delete confirmations
  confirmTitle: 'تأیید',
  deleteQuestionTitle: 'حذف سؤال',
  deleteQuestionBody: 'این سؤال از پیش‌نویس حذف می‌شود. پاسخ‌های نسخه‌های منتشرشده دست نمی‌خورند.',
  deleteReferencedBody: (count: number) =>
    `این سؤال در ${n(count)} قاعده استفاده شده است. پس از حذف، این قاعده‌ها شکسته می‌شوند و تا اصلاح آن‌ها (در زبانهٔ «منطق» یا «CRM») انتشار ممکن نیست:`,
  deletePageTitle: 'حذف صفحه',
  deletePageBody: (count: number) =>
    `این صفحه ${n(count)} مورد دارد که همه حذف می‌شوند.`,
  deletePageJumps: (count: number) =>
    `${n(count)} قاعدهٔ پرش که به این صفحه می‌رود نیز حذف می‌شود.`,
  referenceKind: {
    visibleWhen: 'شرط نمایش',
    requiredWhen: 'شرط الزام',
    jump: 'قاعدهٔ پرش',
    ending: 'شرط پیام پایانی',
    mapping: 'نگاشت CRM',
    automation: 'خودکارسازی',
  } satisfies Record<RuleReferenceKind, string>,
  referenceOf: (kind: string, owner: string) => `${kind} — ${owner}`,
  deleteAnyway: 'حذف',

  // inspector
  inspector: 'ویرایشگر',
  inspectorEmpty: 'یک سؤال، بخش یا صفحه را انتخاب کنید تا اینجا ویرایش شود.',
  closeInspector: 'بستن ویرایشگر',
  editingLanguage: 'زبان متن',
  translationMissing: (language: string) => `ترجمه ندارد — از ${language} نمایش داده می‌شود`,
  questionType: 'نوع سؤال',
  label: 'متن سؤال',
  description: 'توضیح',
  placeholder: 'متن راهنما داخل کادر',
  required: 'الزامی',
  audience: 'چه کسی می‌بیند؟',
  audienceAll: 'همه (عمومی و کارمندان)',
  audienceStaff: 'فقط کارمندان',
  audienceForced: 'انتخاب از CRM همیشه فقط برای کارمندان است.',
  validationMessage: 'پیام خطای سفارشی',
  validationMessageHint: 'اگر خالی بماند، پیام پیش‌فرض نمایش داده می‌شود.',
  answerLines: 'تعداد خطوط پاسخ در نسخهٔ چاپی',
  printSection: 'چاپ',
  rulesSection: 'منطق',
  rulesSummaryNone: 'این سؤال شرطی ندارد.',
  editLogic: 'ویرایش در زبانهٔ منطق',
  showWhenShort: 'نمایش وقتی',
  requiredWhenShort: 'الزامی وقتی',
  choices: 'گزینه‌ها',
  addChoice: 'افزودن گزینه',
  choiceN: (index: number) => `گزینهٔ ${n(index)}`,
  removeChoice: (label: string) => `حذف گزینهٔ «${label}»`,
  moveChoiceUp: (label: string) => `انتقال گزینهٔ «${label}» به بالا`,
  moveChoiceDown: (label: string) => `انتقال گزینهٔ «${label}» به پایین`,
  bulkChoices: 'افزودن چند گزینه (هر خط یک گزینه)',
  bulkAdd: 'افزودن',
  allowOther: 'گزینهٔ «سایر» با متن آزاد',
  otherLabel: 'عنوان گزینهٔ «سایر»',
  choiceUsedWarning: 'این گزینه در یک قاعده استفاده شده است.',
  minLength: 'کمترین تعداد حروف',
  maxLength: 'بیشترین تعداد حروف',
  min: 'کمترین مقدار',
  max: 'بیشترین مقدار',
  minSelected: 'کمترین تعداد انتخاب',
  maxSelected: 'بیشترین تعداد انتخاب',
  scaleMin: 'شروع مقیاس',
  scaleMax: 'پایان مقیاس',
  ratingMax: 'تعداد ستاره',
  scaleMinLabel: 'برچسب ابتدای مقیاس',
  scaleMaxLabel: 'برچسب انتهای مقیاس',
  fileTypes: 'نوع فایل‌های مجاز',
  fileTypeLabels: {
    image: 'تصویر',
    pdf: 'PDF',
    document: 'سند (Word)',
    spreadsheet: 'صفحه‌گسترده (Excel)',
    audio: 'صدا',
  } satisfies Record<FileTypeGroup, string>,
  maxFileMb: 'حداکثر حجم هر فایل (MB)',
  maxFiles: 'حداکثر تعداد فایل',
  consentText: 'متن رضایت‌نامه',
  defaultValue: 'مقدار پیش‌فرض',
  noDefault: 'بدون پیش‌فرض',
  yes: 'بلی',
  no: 'نخیر',
  sectionTitle: 'عنوان بخش',
  blockText: 'متن',
  imageUrl: 'نشانی تصویر (https)',
  imageAlt: 'متن جایگزین تصویر',
  httpsOnly: 'فقط نشانی‌های https پذیرفته می‌شود.',
  dividerHint: 'خط جداکننده تنظیمی ندارد.',
  blockAudience: 'نمایش به',
  pageTitle: 'عنوان صفحه',
  pageDescription: 'توضیح صفحه',
  pageJumpsHint: 'قاعده‌های پرش بعد از این صفحه در زبانهٔ «منطق» تنظیم می‌شوند.',

  // logic
  logicIntro:
    'شرط‌ها فقط می‌توانند به سؤال‌های قبلی اشاره کنند و پرش‌ها فقط به صفحه‌های بعدی می‌روند؛ بنابراین فرم هرگز در حلقه نمی‌افتد.',
  issues: 'بررسی پیش از انتشار',
  noIssues: 'مشکلی پیدا نشد — فرم قابل انتشار است.',
  errorsN: (count: number) => `${n(count)} خطا`,
  warningsN: (count: number) => `${n(count)} هشدار`,
  error: 'خطا',
  warning: 'هشدار',
  showWhen: 'فقط وقتی نمایش داده شود که',
  requiredWhen: 'فقط وقتی الزامی باشد که',
  addShowWhen: 'افزودن شرط نمایش',
  addRequiredWhen: 'افزودن شرط الزام',
  removeRule: 'حذف قاعده',
  modeAll: 'همهٔ شرط‌ها',
  modeAny: 'دست‌کم یکی از شرط‌ها',
  modeLabel: 'نوع ترکیب شرط‌ها',
  addCondition: 'افزودن شرط',
  removeCondition: (index: number) => `حذف شرط ${n(index)}`,
  conditionQuestion: (index: number) => `سؤال شرط ${n(index)}`,
  conditionOperator: (index: number) => `نوع مقایسهٔ شرط ${n(index)}`,
  conditionValue: (index: number) => `مقدار شرط ${n(index)}`,
  noEarlierQuestions: 'پیش از این مورد سؤالی نیست که بتوان به آن شرط گذاشت.',
  operators: {
    eq: 'برابر است با',
    neq: 'برابر نیست با',
    includes: 'شامل',
    excludes: 'شامل نیست',
    gt: 'بزرگ‌تر از',
    gte: 'دست‌کم',
    lt: 'کوچک‌تر از',
    lte: 'حداکثر',
    answered: 'پاسخ داده شده',
    not_answered: 'پاسخ داده نشده',
  } satisfies Record<ConditionOperator, string>,
  otherChoice: 'سایر',
  choiceRemoved: 'گزینهٔ حذف‌شده',
  preview: 'به زبان ساده:',
  afterPage: (index: number) => `بعد از صفحهٔ ${n(index)}`,
  jumpIf: 'اگر',
  jumpGoTo: 'برو به',
  jumpTarget: 'مقصد پرش',
  jumpAlways: 'همیشه (بدون شرط)',
  addJump: 'افزودن قاعدهٔ پرش',
  removeJump: 'حذف قاعدهٔ پرش',
  moveJumpUp: 'بالاتر (اول بررسی شود)',
  noJumps: 'بعد از این صفحه، صفحهٔ بعدی نمایش داده می‌شود.',
  lastPageNoJumps: 'بعد از آخرین صفحه فرم تمام می‌شود.',
  jumpOrderHint: 'قاعده‌ها به ترتیب بررسی می‌شوند و اولین قاعدهٔ برقرار اجرا می‌شود.',
  endWith: (title: string) => `پایان با «${title}»`,
  goToPage: (index: number, title: string) =>
    title === '' ? `صفحهٔ ${n(index)}` : `صفحهٔ ${n(index)} — ${title}`,
  endings: 'پیام‌های پایانی',
  endingsHint:
    'اولین پیام پایانی که شرطش برقرار باشد نمایش داده می‌شود؛ پیام بدون شرط، پیش‌فرض است.',
  endingN: (index: number) => `پیام پایانی ${n(index)}`,
  addEnding: 'افزودن پیام پایانی',
  removeEnding: 'حذف پیام پایانی',
  endingTitle: 'عنوان',
  endingMessage: 'متن پیام',
  endingCondition: 'فقط وقتی نمایش داده شود که',
  endingDefault: 'پیش‌فرض (بدون شرط)',
  addEndingCondition: 'افزودن شرط',
  cannotRemoveLastEnding: 'فرم دست‌کم یک پیام پایانی لازم دارد.',
  sectionsAndQuestions: 'سؤال‌ها و بخش‌ها',
  pageJumps: 'پرش بین صفحه‌ها',

  // appearance
  appearanceBrand: 'رنگ و نشان',
  accent: 'رنگ اصلی',
  logoUrl: 'نشانی لوگو (https)',
  showProgress: 'نمایش نوار پیشرفت',
  showQuestionNumbers: 'نمایش شمارهٔ سؤال‌ها',
  presentation: 'شیوهٔ نمایش',
  presentations: {
    ALL_ON_PAGE: 'همهٔ سؤال‌های هر صفحه با هم',
    ONE_QUESTION: 'یک سؤال در هر نوبت',
  } satisfies Record<FormPresentation, string>,
  welcome: 'صفحهٔ خوش‌آمد',
  welcomeEnabled: 'پیش از فرم یک صفحهٔ خوش‌آمد نمایش داده شود',
  welcomeTitle: 'عنوان',
  welcomeBody: 'متن',
  welcomeButton: 'متن دکمهٔ شروع',
  languages: 'زبان‌های فرم',
  languagesHint:
    'زبان اول پیش‌فرض است. پاسخ‌دهنده می‌تواند زبان را عوض کند؛ متنی که ترجمه ندارد به زبان پیش‌فرض نمایش داده می‌شود.',
  defaultLanguage: 'پیش‌فرض',
  makeDefault: 'پیش‌فرض کن',
  addLanguage: 'افزودن زبان',
  removeLanguage: (language: string) => `حذف زبان ${language}`,
  printInstructions: 'راهنمای بالای نسخهٔ چاپی',

  // crm
  crmMappingTitle: 'نگاشت پاسخ‌ها به CRM',
  crmMappingIntro:
    'نگاشت فقط پیشنهاد می‌دهد: هنگام بررسی پاسخ، کارمند تغییرات پیشنهادی را می‌بیند و تأیید می‌کند. هیچ مقدار موجود بازنویسی نمی‌شود و پاسخ خالی چیزی را پاک نمی‌کند.',
  addMapping: 'افزودن نگاشت',
  removeMapping: 'حذف نگاشت',
  mappingQuestion: 'سؤال',
  mappingField: 'فیلد CRM',
  noCompatibleFields: 'فیلدی سازگار با این نوع سؤال نیست.',
  noMappings: 'هنوز نگاشتی تعریف نشده است.',
  noQuestionsYet: 'اول چند سؤال بسازید.',
  crmFields: {
    'company.name': 'شرکت — نام',
    'company.address': 'شرکت — آدرس',
    'company.domainName': 'شرکت — وب‌سایت',
    'company.businessType': 'شرکت — نوع کسب‌وکار',
    'company.employees': 'شرکت — تعداد کارمندان',
    'person.name': 'مخاطب — نام',
    'person.phone': 'مخاطب — تلفن',
    'person.email': 'مخاطب — ایمیل',
    'person.jobTitle': 'مخاطب — سمت',
    'opportunity.name': 'سرنخ — عنوان',
    'opportunity.interest': 'سرنخ — علاقه (یادداشت)',
    'opportunity.followUp': 'سرنخ — پیگیری (یادداشت)',
  } satisfies Record<CrmTargetField, string>,
  automationsTitle: 'خودکارسازی‌ها',
  automationsWarning:
    'خودکارسازی‌ها روی سرور و برای هر پاسخ ارسال‌شده — از جمله پاسخ‌های لینک عمومی — اجرا می‌شوند. هر اقدام فقط یک بار برای هر پاسخ انجام می‌شود و هیچ مقدار موجودی را بازنویسی نمی‌کند.',
  addAutomation: 'افزودن خودکارسازی',
  removeAutomation: 'حذف خودکارسازی',
  noAutomations: 'هیچ خودکارسازی تعریف نشده است.',
  automationAction: 'اقدام',
  automationActions: {
    CREATE_LEAD: 'ساخت سرنخ',
    CREATE_TASK: 'ساخت وظیفهٔ پیگیری',
    NOTIFY: 'اطلاع به مسئول',
  } satisfies Record<AutomationAction, string>,
  automationEnabled: 'فعال',
  automationCondition: 'فقط وقتی اجرا شود که',
  automationAlways: 'برای هر پاسخ',
  assignee: 'مسئول',
  assigneeDefault: 'مسئول فرم',
  taskTitle: 'عنوان وظیفه',
  dueInDays: 'مهلت (روز بعد از پاسخ)',
  automationN: (index: number) => `خودکارسازی ${n(index)}`,

  // settings
  settingsGeneral: 'مشخصات',
  settingsSaved: 'تنظیمات ذخیره شد',
  settingsSaveFailed: 'تنظیمات ذخیره نشد',
  saveSettings: 'ذخیرهٔ تنظیمات',
  formDescription: 'توضیح (داخلی)',
  owner: 'مسئول فرم',
  publicAccess: 'دسترسی و زمان‌بندی',
  publicEnabled: 'لینک عمومی فعال باشد',
  publicEnabledHint: 'اگر خاموش باشد فرم فقط با ورود کارمند (بازدید یا کاغذی) پر می‌شود.',
  opensAt: 'شروع پذیرش پاسخ',
  closesAt: 'پایان پذیرش پاسخ',
  clearDate: 'پاک کردن',
  responseLimit: 'حداکثر تعداد پاسخ',
  noLimit: 'بدون محدودیت',
  campaigns: 'کمپاین‌ها',
  noCampaigns: 'کمپاینی تعریف نشده است.',
  versions: 'تاریخچهٔ نسخه‌ها',
  noVersions: 'هنوز نسخه‌ای منتشر نشده است.',
  publishedBy: 'منتشرکننده',
  previewVersion: 'پیش‌نمایش',
  printVersion: 'چاپ',
  currentVersion: 'نسخهٔ فعلی',
  statusSection: 'وضعیت فرم',
  currentStatus: 'وضعیت فعلی',
  closeDateBeforeOpen: 'تاریخ پایان باید بعد از تاریخ شروع باشد.',
  nameRequired: 'نام فرم نمی‌تواند خالی باشد.',

  // preview
  previewTitle: 'پیش‌نمایش',
  previewBanner: 'پیش‌نمایش — هیچ پاسخی ثبت نمی‌شود',
  restart: 'شروع دوباره',
  device: 'دستگاه',
  deviceDesktop: 'رایانه',
  deviceMobile: 'موبایل',
  mode: 'حالت',
  modeOnline: 'آنلاین',
  modePrint: 'چاپی',
  language: 'زبان',
  version: 'نسخه',
  draftVersion: 'پیش‌نویس فعلی',
  asStaff: 'نمایش به‌عنوان کارمند',
  asStaffHint: 'سؤال‌های مخصوص کارمندان هم نمایش داده می‌شوند.',
  backToBuilder: 'بازگشت به سازنده',
  versionNotFound: 'این نسخه پیدا نشد؛ پیش‌نویس نمایش داده می‌شود.',
  printFrameTitle: 'پیش‌نمایش نسخهٔ چاپی',
  openPrint: 'باز کردن صفحهٔ چاپ',
};

export const formatCount = n;
