import { type ReviewFilter } from './responses/responseQuery';

// Dari UI text for the responses table, response detail and CRM review.
export const TSR = {
  title: 'پاسخ‌ها',
  sub: 'همهٔ پاسخ‌های فرم‌ها — آنلاین، حضوری و کاغذی',
  count: (shown: string, total: string) => `${shown} از ${total} پاسخ`,
  loadMore: 'نمایش بیشتر',
  loading: 'در حال بارگذاری…',
  empty: 'پاسخی با این فیلترها پیدا نشد',
  emptyForm: 'این فرم هنوز پاسخی ندارد',
  clearFilters: 'پاک کردن فیلترها',
  filters: 'فیلترها',
  searchPlaceholder: 'جستجو در نام پاسخ…',
  allForms: 'همهٔ فرم‌ها',
  allVersions: 'همهٔ نسخه‌ها',
  allCampaigns: 'همهٔ کمپاین‌ها',
  allSources: 'همهٔ منابع',
  allCollectors: 'همهٔ جمع‌آوری‌کنندگان',
  allCompletion: 'تکمیل: همه',
  anyLinkage: 'ارتباط با CRM: همه',
  linked: 'وصل به CRM',
  unlinked: 'بدون ارتباط با CRM',
  city: 'شهر',
  area: 'ناحیه',
  from: 'از تاریخ',
  to: 'تا تاریخ',
  form: 'فرم',
  version: 'نسخه',
  source: 'منبع',
  collector: 'جمع‌آوری‌کننده',
  enteredBy: 'واردکننده',
  campaign: 'کمپاین',
  completion: 'وضعیت تکمیل',
  review: 'وضعیت بررسی',
  collectedAt: 'تاریخ جمع‌آوری',
  submittedAt: 'تاریخ ارسال',
  enteredAt: 'تاریخ ورود کاغذی',
  crm: 'CRM',
  respondent: 'پاسخ‌دهنده',
  noName: 'بدون نام',
  columns: 'ستون‌ها',
  columnsHint: 'سؤال‌هایی که در جدول دیده شوند (برای همین فرم روی این دستگاه ذخیره می‌شود)',
  columnsNeedForm: 'برای انتخاب ستون پاسخ‌ها، یک فرم را انتخاب کنید',
  selectAll: 'انتخاب همه',
  selected: (count: string) => `${count} انتخاب شد`,
  bulkReview: 'تغییر وضعیت بررسی',
  bulkApply: 'اعمال',
  bulkProgress: (done: string, total: string) => `${done} از ${total}…`,
  bulkDone: (done: string, failed: string) => `${done} پاسخ به‌روز شد${failed === '۰' ? '' : ` — ${failed} ناموفق`}`,
  exportCsv: 'خروجی CSV',
  exportXlsx: 'خروجی Excel',
  exporting: 'در حال آماده‌سازی خروجی…',
  exportDone: (count: string) => `${count} پاسخ صادر شد`,
  exportFailed: 'خروجی گرفته نشد',
  exportHint: 'خروجی همهٔ پاسخ‌های فیلتر فعلی را شامل می‌شود',
  enterPaper: 'ورود پاسخ کاغذی',
  collect: 'جمع‌آوری حضوری',
  open: 'باز کردن',
  back: 'بازگشت',
  notFound: 'این پاسخ پیدا نشد یا اجازهٔ دیدن آن را ندارید.',
  // detail
  print: 'چاپ',
  answers: 'پاسخ‌ها',
  metadata: 'مشخصات',
  paperRef: 'شمارهٔ برگه',
  transcriptionNotes: 'یادداشت‌های ورود کاغذی',
  location: 'موقعیت',
  openMap: 'نمایش روی نقشه',
  buyingInterest: 'علاقه به خرید',
  visit: 'بازدید',
  visitOutcome: 'نتیجهٔ بازدید',
  language: 'زبان',
  changeStatus: 'تغییر',
  statusSaved: 'وضعیت ذخیره شد',
  statusFailed: 'وضعیت ذخیره نشد',
  staffOnlyBadge: 'فقط کارمندان',
  notInVersion: 'در این نسخه نبود',
  answerCounts: (answered: string, unanswered: string, skipped: string) =>
    `${answered} پاسخ داده · ${unanswered} بی‌پاسخ · ${skipped} رد شده طبق منطق`,
  noQuestions: 'این نسخه سؤالی ندارد',
  versionMissing: 'نسخهٔ این پاسخ پیدا نشد؛ پاسخ‌ها به‌صورت خام نمایش داده می‌شوند.',
  // corrections
  editAnswers: 'ویرایش پاسخ‌ها',
  editTitle: 'اصلاح پاسخ‌ها',
  editHint: 'اصلاحات با همان قواعد فرم بررسی می‌شوند و در تاریخچه ثبت می‌گردند.',
  saveComplete: 'ذخیره به‌عنوان تکمیل‌شده',
  savePartial: 'ذخیره به‌عنوان ناتمام',
  correctionSaved: 'اصلاحات ذخیره شد',
  correctionInvalid: 'برخی پاسخ‌ها معتبر نیستند؛ موارد مشخص‌شده را اصلاح کنید.',
  correctionFailed: 'ذخیره نشد',
  // notes / attachments / tasks
  notes: 'یادداشت‌ها',
  noNotes: 'هنوز یادداشتی نیست',
  addNote: 'افزودن یادداشت',
  notePlaceholder: 'یادداشت داخلی دربارهٔ این پاسخ…',
  noteTitle: 'یادداشت پاسخ نظرسنجی',
  attachments: 'فایل‌ها و اسکن‌ها',
  noAttachments: 'فایلی پیوست نشده',
  upload: 'بارگذاری اسکن / عکس',
  uploading: 'در حال بارگذاری…',
  uploadFailed: 'بارگذاری ناموفق بود',
  followUp: 'پیگیری',
  followUpTitle: 'عنوان کار پیگیری',
  followUpDue: 'موعد',
  followUpAssignee: 'مسئول',
  followUpCreate: 'ایجاد کار پیگیری',
  followUpCreated: 'کار پیگیری ایجاد شد',
  followUpLinkedLead: 'به سرنخ وصل‌شده هم پیوند می‌شود',
  followUpDefault: (name: string) => `پیگیری پاسخ نظرسنجی — ${name}`,
  tasks: 'کارهای پیگیری',
  noTasks: 'کار پیگیری ثبت نشده',
  // automations
  automations: 'اقدام‌های CRM و خودکار',
  noAutomations: 'هنوز اقدامی برای این پاسخ ثبت نشده',
  retry: 'اجرای دوباره',
  retrying: 'در حال اجرا…',
  retryDone: 'اقدام‌های خودکار دوباره اجرا شد',
  retryFailed: 'اجرا ناموفق بود',
  actionStatus: { DONE: 'انجام شد', FAILED: 'ناموفق', SUGGESTED: 'پیشنهادی' } as Record<string, string>,
  actionTypes: {
    CREATE_LEAD: 'ایجاد سرنخ',
    CREATE_TASK: 'ایجاد کار',
    NOTIFY: 'اطلاع‌رسانی',
    SUGGESTED_LINK: 'پیشنهاد پیوند',
    LINK: 'پیوند',
    CREATE: 'ایجاد',
    APPLY: 'اعمال تغییرات',
  } as Record<string, string>,
  history: 'تاریخچهٔ تغییرات',
  noHistory: 'تغییری ثبت نشده',
  // CRM panel
  crmPanel: 'پیوند با CRM',
  crmHint: 'هیچ چیزی خودکار ساخته یا بازنویسی نمی‌شود؛ هر تغییر را خودتان تأیید می‌کنید.',
  company: 'شرکت',
  contact: 'مخاطب',
  lead: 'سرنخ',
  notLinked: 'وصل نشده',
  linkExisting: 'وصل به مورد موجود',
  unlink: 'قطع پیوند',
  create: 'ایجاد',
  createCompany: 'ایجاد شرکت',
  createContact: 'ایجاد مخاطب',
  createLead: 'ایجاد سرنخ',
  creating: 'در حال ایجاد…',
  linking: 'در حال پیوند…',
  alreadyLinked: 'این پاسخ در این فاصله توسط کس دیگری وصل شده بود؛ همان مورد نگه داشته شد.',
  suggestions: 'پیشنهادها',
  invitationSuggestion: 'پیشنهادشده توسط لینک دعوت — دلیل هویت نیست',
  useSuggestion: 'وصل کن',
  duplicates: 'موارد مشابه در CRM',
  noDuplicates: 'مورد مشابهی پیدا نشد',
  matchReason: { name: 'نام مشابه', phone: 'شمارهٔ یکسان', email: 'ایمیل یکسان' } as Record<string, string>,
  matchKind: { lead: 'سرنخ', company: 'شرکت', person: 'مخاطب' } as Record<string, string>,
  nameMatchWarning: 'تشابه نام به معنی یکی بودن نیست — پیش از وصل کردن بررسی کنید.',
  companyName: 'نام شرکت',
  street: 'آدرس',
  employees: 'تعداد کارمندان',
  businessType: 'نوع کسب‌وکار',
  firstName: 'نام',
  lastName: 'تخلص',
  phone: 'شماره تلفن',
  email: 'ایمیل',
  jobTitle: 'وظیفه',
  leadName: 'نام سرنخ',
  askActioned: 'سرنخ وصل شد. وضعیت بررسی به «اقدام‌شده» تغییر کند؟',
  markActioned: 'بلی، اقدام‌شده',
  keepStatus: 'نخیر',
  applyChanges: 'اعمال تغییرات پیشنهادی',
  applyHint: 'فقط فیلدهای انتخاب‌شده به‌روز می‌شوند. پاسخ خالی هرگز مقدار CRM را پاک نمی‌کند.',
  loadDiff: 'مقایسه با CRM',
  field: 'فیلد',
  current: 'مقدار فعلی CRM',
  proposed: 'پاسخ فرم',
  blankKept: 'پاسخ خالی — مقدار CRM حفظ می‌شود',
  keepCurrent: 'حفظ مقدار فعلی',
  useAnswer: 'جایگزینی با پاسخ',
  noChanges: 'تغییری برای اعمال نیست — CRM با پاسخ‌ها یکسان است.',
  noMapping: 'این فرم نگاشت CRM ندارد.',
  applying: 'در حال اعمال…',
  applied: (count: string) => `${count} تغییر اعمال شد`,
  applyFailed: 'اعمال تغییرات ناموفق بود',
  interestNoteTitle: 'علاقه (از نظرسنجی)',
  needLinkFor: 'برای اعمال، ابتدا این مورد را وصل کنید',
  cardTitle: 'نظرسنجی‌ها و فرم‌ها',
  cardEmpty: 'هنوز نظرسنجی‌ای ثبت نشده',
  cancel: 'لغو',
  save: 'ذخیره',
  close: 'بستن',
};

export const REVIEW_FILTER_LABELS: Record<ReviewFilter, string> = {
  '': 'بررسی: همه به‌جز هرزنامه',
  ALL: 'بررسی: همه (با هرزنامه)',
  NEW: 'جدید',
  NEEDS_REVIEW: 'نیاز به بررسی',
  REVIEWED: 'بررسی‌شده',
  ACTIONED: 'اقدام‌شده',
  SPAM: 'هرزنامه',
};

export const CRM_FIELD_LABELS: Record<string, string> = {
  'company.name': 'نام شرکت',
  'company.address': 'آدرس شرکت',
  'company.domainName': 'وب‌سایت',
  'company.businessType': 'نوع کسب‌وکار',
  'company.employees': 'تعداد کارمندان',
  'person.name': 'نام مخاطب',
  'person.phone': 'تلفن مخاطب',
  'person.email': 'ایمیل مخاطب',
  'person.jobTitle': 'وظیفهٔ مخاطب',
  'opportunity.name': 'نام سرنخ',
  'opportunity.interest': 'علاقه (یادداشت روی سرنخ)',
  'opportunity.followUp': 'پیگیری (کار روی سرنخ)',
};
