import { type AttachmentKind } from './assistantContext';

// AI assistant and AI usage report. Kept out of strings.ts, which every
// branch appends to.
export const TAI = {
  nav: 'دستیار هوشمند',
  title: 'دستیار هوشمند',
  sub: 'هر سؤالی دربارهٔ فروش، لیدها و مشتریان بپرسید',
  newChat: 'گفتگوی جدید',
  history: 'تاریخچهٔ گفتگوها',
  historyEmpty: 'هنوز گفتگویی ندارید.',
  searchHistory: 'جستجو در گفتگوها…',
  untitled: 'گفتگوی بدون عنوان',
  loadFailed: 'بارگذاری گفتگوها ممکن نشد.',
  messagesFailed: 'بارگذاری پیام‌ها ممکن نشد.',
  archive: 'حذف از تاریخچه',
  archiveConfirm: 'این گفتگو از تاریخچه حذف شود؟',
  emptyTitle: 'از کجا شروع کنیم؟',
  emptyHint:
    'لید، مخاطب، شرکت یا نظرسنجی را با دکمهٔ 📎 پیوست کنید تا دستیار با اطلاعات همان رکورد جواب بدهد.',
  placeholder: 'پیام خود را بنویسید…',
  attach: 'پیوست رکورد',
  removeAttachment: 'برداشتن پیوست',
  preparingContext: 'در حال آماده‌سازی پیوست‌ها…',
  attachFailed: 'خواندن این رکورد ممکن نشد:',
  scrollToBottom: 'رفتن به آخرین پیام',
  showHistory: 'تاریخچه',
  hideHistory: 'بستن تاریخچه',
  tokens: 'توکن',
  threadTokens: 'مصرف این گفتگو',
  myUsage: 'مصرف شما در ۳۰ روز گذشته',
  pickerTitle: 'پیوست رکورد به پیام',
  pickerSearch: 'نام را جستجو کنید…',
  pickerHint: 'حداقل دو حرف بنویسید.',
  pickerEmpty: 'چیزی پیدا نشد.',
  pickerSearching: 'در حال جستجو…',
  pickerDone: 'تمام',
  pickerSelected: 'انتخاب‌شده',
  suggestions: [
    'امروز با کدام لیدها تماس بگیرم؟',
    'برای این لید یک پیام پیگیری واتس‌اپ بنویس.',
    'نتیجهٔ این نظرسنجی را خلاصه کن و فرصت فروش را بگو.',
  ],
  // ---- usage report ----
  usageTitle: 'مصرف توکن هوش مصنوعی',
  usageSub: 'چه کسی چقدر از هوش مصنوعی استفاده کرده است',
  usageCard: 'مصرف هوش مصنوعی',
  usageCardSub: 'توکن مصرف‌شدهٔ هر کاربر، گفتگو و خلاصه‌ها',
  rangeToday: 'امروز',
  range7d: '۷ روز',
  range30d: '۳۰ روز',
  range90d: '۹۰ روز',
  range365d: 'یک سال',
  kpiTotal: 'مجموع توکن',
  kpiRequests: 'درخواست‌ها',
  kpiUsers: 'کاربران فعال',
  kpiCost: 'هزینهٔ تخمینی',
  trend: 'روند مصرف',
  byUser: 'مصرف به تفکیک کاربر',
  colUser: 'کاربر',
  colRequests: 'درخواست',
  colInput: 'ورودی',
  colOutput: 'خروجی',
  colChat: 'گفتگو',
  colOther: 'خلاصه و سایر',
  colTotal: 'مجموع',
  colShare: 'سهم',
  colLastUsed: 'آخرین استفاده',
  colCost: 'هزینه',
  systemUser: 'خودکار (ورکفلو و ایجنت‌ها)',
  unknownUser: 'کاربر حذف‌شده',
  noUsage: 'در این بازه مصرفی ثبت نشده است.',
  forbidden: 'این گزارش فقط برای مدیران است.',
  unsupported: 'این گزارش پس از به‌روزرسانی سرور فعال می‌شود.',
  usageLoadFailed: 'بارگذاری گزارش ممکن نشد.',
  trackedSince: 'خلاصه‌ها و فراخوانی‌های تک‌مرحله‌ای از این تاریخ شمرده می‌شوند:',
  chatHistoryNote: 'گفتگوهای قبلی از تاریخچهٔ گفتگوها محاسبه شده‌اند.',
  refresh: 'تازه‌سازی',
} as const;

export const ATTACHMENT_KIND_LABELS: Record<AttachmentKind, string> = {
  lead: 'لید',
  person: 'مخاطب',
  company: 'شرکت',
  survey: 'نظرسنجی',
  task: 'وظیفه',
  note: 'یادداشت',
};
