// Audit trail: the security log of who did what, and the screens that read it.
export const TAUDIT = {
  auditNav: 'گزارش فعالیت',
  auditTitle: 'گزارش فعالیت کاربران',
  auditSubtitle: 'هر کاری که کاربران در برنامه انجام می‌دهند — همراه با نشانه‌های کپی، چاپ و اسکرین‌شات',
  auditLoadFailed: 'بارگیری گزارش ناموفق بود',
  auditEmpty: 'رویدادی با این فیلترها ثبت نشده',
  auditMore: 'نمایش بیشتر',
  auditLoading: 'در حال بارگیری…',
  auditAdminOnly: 'این بخش فقط برای مدیران است',
  auditUnsupported:
    'این بخش روی این نسخه فعال نیست — اسکریپت provision-audit-log اجرا نشده',
  auditPending: 'رویداد ارسال‌نشده',
  auditFilterActor: 'کاربر',
  auditFilterCategory: 'نوع',
  auditFilterSeverity: 'حساسیت',
  auditFilterAll: 'همه',
  auditFilterToday: 'امروز',
  auditFilter7d: '۷ روز',
  auditFilter30d: '۳۰ روز',
  auditFilterAllTime: 'همه',
  auditSearchPlaceholder: 'جستجو در کاربر، مسیر، شناسه…',
  auditRefresh: 'تازه‌سازی',
  auditClockSkew: 'اختلاف ساعت',
  auditOn: 'روی',
  auditVia: 'با',
  auditSensitiveOnly: 'فقط موارد حساس',
  auditActorSearch: 'جستجوی کاربر…',
  auditActorEveryone: 'همهٔ کاربران',
  auditActorNoMatch: 'کاربری با این نام پیدا نشد',
  auditActorFailed: 'جستجوی کاربر ناموفق بود',
  auditActorClear: 'حذف فیلتر کاربر',
  auditRetentionPruned: 'پاک‌سازی خودکار گزارش',

  auditCategory: {
    auth: 'ورود و خروج',
    navigation: 'پیمایش',
    read: 'مشاهده',
    write: 'تغییر',
    delete: 'حذف',
    exfiltration: 'خروج داده',
    security: 'امنیتی',
  } as Record<string, string>,

  auditSeverity: {
    info: 'عادی',
    notice: 'قابل توجه',
    sensitive: 'حساس',
    critical: 'بحرانی',
  } as Record<string, string>,

  auditEventType: {
    'session.start': 'شروع نشست',
    'session.end': 'پایان نشست',
    'session.background': 'رفتن به پس‌زمینه',
    'session.foreground': 'بازگشت به برنامه',
    'auth.logout': 'خروج از حساب',
    'auth.failed': 'ورود ناموفق',
    'screen.view': 'باز کردن صفحه',
    'record.read': 'مشاهده رکورد',
    'record.create': 'ساخت رکورد',
    'record.update': 'ویرایش رکورد',
    'record.upsert': 'ثبت رکورد',
    'record.merge': 'ادغام رکورد',
    'record.restore': 'بازگردانی رکورد',
    'record.delete': 'حذف رکورد',
    'record.destroy': 'حذف دائمی رکورد',
    'export.copy': 'کپی متن',
    'export.cut': 'برش متن',
    'export.clipboard': 'کپی در کلیپ‌بورد',
    'export.print': 'چاپ / خروجی PDF',
    'export.print_shortcut': 'میان‌بر چاپ',
    'file.download': 'دانلود فایل',
    'contact.reach_out': 'تماس با مشتری',
    'screenshot.suspected': 'اسکرین‌شات احتمالی',
    'permission.denied': 'دسترسی رد شد',
    'api.error': 'خطای سرور',
    'audit.buffer_overflow': 'از دست رفتن رویداد',
    'audit.retention_pruned': 'پاک‌سازی خودکار گزارش',
  } as Record<string, string>,
};
