export type SurveyPrintPhrases = {
  and: string;
  or: string;
  yes: string;
  no: string;
  answered: (question: string) => string;
  notAnswered: (question: string) => string;
  equals: (question: string, value: string) => string;
  notEquals: (question: string, value: string) => string;
  includes: (question: string, value: string) => string;
  excludes: (question: string, value: string) => string;
  greaterThan: (question: string, value: string) => string;
  atLeast: (question: string, value: string) => string;
  lessThan: (question: string, value: string) => string;
  atMost: (question: string, value: string) => string;
  question: (number: string) => string;
  answerOnlyIf: (condition: string) => string;
  requiredIf: (condition: string) => string;
  goTo: (condition: string, question: string) => string;
  finish: (condition: string) => string;
  goToAlways: (question: string) => string;
  finishAlways: string;
  jumpRule: string;
  conditionalEndingNote: string;
  staffOnlyOmittedNote: (count: string) => string;
  alternativeFile: string;
  alternativeLocation: string;
  alternativeCompany: string;
  alternativeContact: string;
  alternativeLead: string;
  alternativeImage: string;
  unprintableReference: (what: string) => string;
};
